### ISSUE TITLE
Ore Excavation/FTB Ultimine

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#84]
1. https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine
2. https://www.curseforge.com/minecraft/mc-mods/ore-excavation

both do the same thing except FTB ultimine has more features.

I vote we remove ore excavation

**Comment by Lixquid** [comment]
Ore Excavation allows you to define a user-made pattern of excavation, whereas ultimine just has presets.

They're both useful because they both do a couple of things slightly better; ultimine clears grass / builds staircases better, Ore Excavation is better at fine control like building rooms underground

**Comment by mcd1992** [comment]
Yes please keep oreexcavation, it handles crops/grass ect. better.

**Comment by SwadicalRag** [comment]
Didn't know that oreex also had similar features. Given that's the case I vote to remove ftb ultimine
